In [36]:
import pandas as pd

file_path1 = r"C:\Users\bluecom011\Desktop\정리한거\사회복지수.csv"

data_복지수 = pd.read_csv(file_path1, encoding='cp949')

data_복지수.head(10)

  시군구명  개수
0  강남구  56
1  강동구  51
2  강북구  30
3  강서구  59
4  관악구  25
5  광진구  15
6  구로구  25
7  금천구  23
8  노원구  58
9  도봉구  24

In [35]:

import pandas as pd

file_path2 = r"C:\Users\bluecom011\Desktop\정리한거\서울특별시_장애인 주차구역 과태료 부과 현황_20230209 (2).CSV"

data_과태료 = pd.read_csv(file_path2, encoding='cp949')

data_과태료.head(8)

    자치구    건수      부과액
0   종로구   892   75000260
1    중구  2154  185440000
2   용산구  1438  138260000
3   성동구  2264  195190000
4   광진구  1594  133660000
5  동대문구  5432  448580000
6   중랑구  1573  132493000
7   성북구  1336  114600000

In [38]:
import pandas as pd
# '시군구명'과 '자치구' 열을 기준으로 두 데이터 프레임을 병합
merged_data = pd.merge(data_복지수, data_과태료, left_on='시군구명', right_on='자치구')

# '자치구' 열은 중복되므로 삭제
merged_data = merged_data.drop('시군구명', axis=1)

# 결과 확인
print(merged_data)
# CSV 파일로 저장
merged_data.to_csv('복지수_과태료.csv', index=False, encoding='utf-8')

    개수   자치구    건수      부과액
0   56   강남구  6135  546904200
1   51   강동구  2307  184200000
2   30   강북구  1745  148504000
3   59   강서구  5443  447509000
4   25   관악구  1776  152020000
5   15   광진구  1594  133660000
6   25   구로구  2355  209330000
7   23   금천구  2208  208510000
8   58   노원구  2521  201200000
9   24   도봉구  1948  169470000
10   9  동대문구  5432  448580000
11  21   동작구  1982  161890000
12  24   마포구  3096  269650000
13  19  서대문구  1245  124500000
14  30   서초구  3257  269840000
15  15   성동구  2264  195190000
16  10   성북구  1336  114600000
17  50   송파구  4656  409090000
18  24   양천구  1977  171680000
19  22  영등포구  4902  451500000
20  12   용산구  1438  138260000
21  39   은평구  1220  108620000
22  13   종로구   892   75000260
23  11    중구  2154  185440000
24  14   중랑구  1573  132493000

In [40]:

import pandas as pd

file_path3 =r"C:\Users\bluecom011\Desktop\정리한거\주차장 동별.csv"

data_주차장 = pd.read_csv(file_path3, encoding='utf-8')

data_주차장.head(8)

    동별     2020
0   동별       합계
1   동별       소계
2   동별  개소 (개소)
3   소계   317181
4  종로구     7111
5   중구     4233
6  용산구     7441
7  성동구     6659

In [42]:
merged_data2 = pd.merge(data_주차장, merged_data, left_on='동별', right_on='자치구')

# '자치구' 열은 중복되므로 삭제
merged_data2 = merged_data2.drop('동별', axis=1)
# 결과 확인
print(merged_data2)
# CSV 파일로 저장
merged_data2.to_csv('복지수_과태료_주차장.csv', index=False, encoding='utf-8')

     2020  개수   자치구    건수      부과액
0    7111  13   종로구   892   75000260
1    4233  11    중구  2154  185440000
2    7441  12   용산구  1438  138260000
3    6659  15   성동구  2264  195190000
4   19566  15   광진구  1594  133660000
5   10293   9  동대문구  5432  448580000
6   12438  14   중랑구  1573  132493000
7   13084  10   성북구  1336  114600000
8   11107  30   강북구  1745  148504000
9    9736  24   도봉구  1948  169470000
10   6780  58   노원구  2521  201200000
11  18901  39   은평구  1220  108620000
12  11461  19  서대문구  1245  124500000
13  13158  24   마포구  3096  269650000
14  11677  24   양천구  1977  171680000
15  18858  59   강서구  5443  447509000
16  10643  25   구로구  2355  209330000
17   9152  23   금천구  2208  208510000
18  10907  22  영등포구  4902  451500000
19   8501  21   동작구  1982  161890000
20  20871  25   관악구  1776  152020000
21  12388  30   서초구  3257  269840000
22  19861  56   강남구  6135  546904200
23  22671  50   송파구  4656  409090000
24  19684  51   강동구  2307  184200000

In [46]:
import pandas as pd

file_path4 =r"C:\Users\bluecom011\Desktop\정리한거\장애인 인구.csv"

data_인구 = pd.read_csv(file_path4, encoding='utf-8')

data_인구.head(8)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 1: invalid start byte

In [ ]:
import matplotlib.pyplot as plt

# 변수1과 변수2의 산점도 그리기
plt.scatter(data_pay['근무지역'], data_pay['변수2'])
plt.title('변수1과 변수2의 산점도')
plt.xlabel('변수1')
plt.ylabel('변수2')
plt.show()

In [14]:
# Specify the columns you want to keep
desired_columns = ['동별', '2020']

# Select only the desired columns
selected_data = data_pay[desired_columns]

# Display the DataFrame with only the selected columns
selected_data.head(5)
# Save the DataFrame to a CSV file
selected_data.to_csv('주차장 동별.csv', index=False)