In [17]:

import pandas as pd

file_path1 = r'C:\Users\bluecom011\Desktop\분석할거\seoul_traffic.csv'
file_path2 = r'C:\Users\bluecom011\Desktop\분석할거\도로혼잡도정리.csv'
file_path3 = r'C:\Users\bluecom011\Desktop\분석할거\복지수_과태료_주차장.csv'
file_path4 = r'C:\Users\bluecom011\Desktop\분석할거\장애인 인구.csv'
file_path5 = r'C:\Users\bluecom011\Desktop\분석할거\장애인 취업정보.csv'

data_traffic = pd.read_csv(file_path1, encoding='utf-8')
data_congestion = pd.read_csv(file_path2, encoding='utf-8')
data_welfare = pd.read_csv(file_path3, encoding='utf-8')
data_population_disability = pd.read_csv(file_path4, encoding='utf-8')
data_employment_disability = pd.read_csv(file_path5, encoding='utf-8')

# Now you have loaded data from different files into different variables.
# You can use these variables for further analysis.


data_traffic.head(8)

   Unnamed: 0  FRIN_CG sigungu_name     emd_name
0           0    85.16          종로구          사직동
1           1    45.41          종로구          삼청동
2           2    27.78          종로구          부암동
3           3    69.59          종로구          평창동
4           4    53.07          종로구          무악동
5           5    72.20          종로구          교남동
6           6    51.56          종로구          가회동
7           7    67.49          종로구  종로1·2·3·4가동

In [18]:
data_congestion.head()

,Unnamed: 0,상권명,자치구,주요도로망 Level5.5 네트워크 기준 인근 도로수,각 링크별 혼잡빈도강도 중 최솟값,각 링크별 혼잡빈도강도 중 최댓값,각 링크별 혼잡빈도강도의 평균값
0,0,공덕역_1,마포구,24,13,100,64.8
1,1,공덕역_2,마포구,12,13,100,53.5
2,2,디지털미디어시티,마포구,20,17,75,38.3
3,3,마포역_1,마포구,30,13,100,71.9
4,4,마포역_2,마포구,30,37,100,77.3

In [32]:
data_welfare.head(5)

     주차장  복지시설  자치구    건수      부과액
0   7111    13  종로구   892   75000260
1   4233    11   중구  2154  185440000
2   7441    12  용산구  1438  138260000
3   6659    15  성동구  2264  195190000
4  19566    15  광진구  1594  133660000

In [20]:
data_population_disability.head()

  Unnamed: 0     2020     2021     2022
0         소계  394,190  392,123  391,859
1        종로구    6,015    5,929    5,834
2         중구    5,700    5,634    5,552
3        용산구    7,960    7,686    7,621
4        성동구   11,412   11,284   11,092

In [21]:
data_employment_disability.head(5)

   Unnamed: 0        취업일자    연령   장애유형 중증여부         취업직종대분류  자치구
0           0  2022-04-18  25.0   청각장애   경증       경영·행정·사무직  송파구
1           1  2022-04-18  27.0  뇌병변장애   중증       경영·행정·사무직  송파구
2           2  2022-04-18  28.0   심장장애   중증       경영·행정·사무직  송파구
3           3  2022-10-21  68.0   지체장애   경증  청소 및 기타 개인서비스직  서초구
4           4  2022-05-09  52.0   지체장애   경증  청소 및 기타 개인서비스직  서초구

In [28]:
import pandas as pd

# data_welfare와 data_congestion 데이터프레임을 자치구를 기준으로 병합
merged_data = pd.merge(data_welfare, data_congestion, on='자치구', how='inner')

# 또는 pd.concat()을 사용하여 이어붙이기
# merged_data = pd.concat([data_welfare.set_index('자치구'), data_congestion.set_index('자치구')], axis=1, join='inner')

# 결과 확인
print(merged_data)
merged_data.to_csv('merged_data.csv', encoding='utf-8-sig', index=False)

       주차장  복지시설  자치구    건수      부과액    Unnamed: 0     상권명  \
0     7111    13  종로구   892   75000260          10  서대문역_1
1     7111    13  종로구   892   75000260          28  경복궁역_1
2     7111    13  종로구   892   75000260          29  경복궁역_2
3     7111    13  종로구   892   75000260          30  광화문역_1
4     7111    13  종로구   892   75000260          31  광화문역_2
..     ...   ...  ...   ...        ...         ...     ...
247  19684    51  강동구  2307  184200000         110     길동역
248  19684    51  강동구  2307  184200000         111    둔촌동역
249  19684    51  강동구  2307  184200000         112     명일역
250  19684    51  강동구  2307  184200000         113   천호역_1
251  19684    51  강동구  2307  184200000         114   천호역_2

     주요도로망 Level5.5 네트워크 기준 인근 도로수  각 링크별 혼잡빈도강도 중 최솟값  각 링크별 혼잡빈도강도 중 최댓값  \
0                               16                  24                 100
1                               20                  12                 100
2                               10                  36                 100
3                               22                  12                 100
4                               39                  13                 100
..                             ...                 ...                 ...
247                             22                   3                 100
248                             10                  11                  75
249                             14                  14                  79
250                             13                  26                 100
251                             19                  26                 100

     각 링크별 혼잡빈도강도의 평균값
0                 67.9
1                 81.8
2                 80.1
3                 72.6
4                 80.8
..                 ...
247               62.3
248               40.7
249               51.4
250               74.2
251               69.0

[252 rows x 11 columns]

In [ ]:
import pandas as pd

# data_welfare와 data_congestion 데이터프레임을 자치구를 기준으로 병합
merged_data2 = pd.merge(data_welfare, data_congestion, on='자치구', how='inner')

# 또는 pd.concat()을 사용하여 이어붙이기
# merged_data = pd.concat([data_welfare.set_index('자치구'), data_congestion.set_index('자치구')], axis=1, join='inner')

# 결과 확인
print(merged_data)
merged_data.to_csv('merged_data.csv', encoding='utf-8-sig', index=False)

In [35]:
import pandas as pd
from scipy.stats import chi2_contingency
# '건수'와 '주차장'가 범주형 열입니다.
# numerical_column1 = '건수'
# numerical_column2 = '주차장'

contingency_table = pd.crosstab(merged_data['주차장'], merged_data['부과액  '])

# 카이제곱 검정 수행
chi2, p, _, _ = chi2_contingency(contingency_table)

# 결과 출력
print("카이제곱 검정 통계량:", chi2)
print("p-value:", p)

카이제곱 검정 통계량: 6048.0
p-value: 0.0

In [30]:
import pandas as pd

# '건수'와 '각 링크별 혼잡빈도강도의 평균값'가 각각 연속형 변수로 가정합니다.
numerical_column1 = '건수'
numerical_column2 = '각 링크별 혼잡빈도강도의 평균값'

# 데이터프레임에서 두 변수 간의 피어슨 상관계수 계산
correlation = merged_data[numerical_column1].corr(merged_data[numerical_column2])

# 상관계수 출력
print(f'피어슨 상관계수: {correlation}')

피어슨 상관계수: -0.3321525986130525

In [36]:
import pandas as pd
from scipy.stats import chi2_contingency
# '건수'와 '주차장'가 범주형 열입니다.
# numerical_column1 = '건수'
# numerical_column2 = '주차장'

contingency_table = pd.crosstab(data_welfare['복지시설'], data_welfare['부과액  '])

# 카이제곱 검정 수행
chi2, p, _, _ = chi2_contingency(contingency_table)

# 결과 출력
print("카이제곱 검정 통계량:", chi2)
print("p-value:", p)

카이제곱 검정 통계량: 474.9999999999999
p-value: 0.2602342853617173

## 군집분석

In [ ]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

# 데이터 불러오기 (불법주차 건수, 센서 입지 등의 변수 포함)
# 여기서는 예시로 임의의 데이터를 사용하겠습니다. 실제 데이터에 맞게 수정 필요
file_path = 'your_data.csv'
data = pd.read_csv(file_path)

# 필요한 변수 선택 (예: 불법주차 건수, 센서 입지 변수 등)
selected_features = ['불법주차건수', '센서입지1', '센서입지2', ...]

# 선택한 변수만으로 데이터프레임 생성
X = data[selected_features]

# 데이터 표준화 (Standardization)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 군집분석 (K-means 알고리즘 사용)
kmeans = KMeans(n_clusters=3, random_state=42)  # 군집의 개수는 조절 가능
data['Cluster'] = kmeans.fit_predict(X_scaled)

# 군집 결과 확인
print(data[['불법주차건수', 'Cluster']])

# 군집별 특성 확인 (평균 값 등)
cluster_summary = data.groupby('Cluster').mean()
print(cluster_summary)

# 시각화 등을 통해 군집 결과를 살펴봅니다.
# 예시로 2차원 시각화 (실제 데이터에 따라 조정 필요)
plt.scatter(X_scaled[:, 0], X_scaled[:, 1], c=data['Cluster'], cmap='viridis')
plt.title('Cluster Analysis')
plt.xlabel('불법주차건수 (Standardized)')
plt.ylabel('센서입지1 (Standardized)')
plt.show()